{
  "buildCommand": "npm install --prefix backend && npm run build --prefix frontend",
  "installCommand": "npm install --prefix backend && npm install --prefix frontend",
  "startCommand": "node backend/server.js",
  "env": {
    "MONGODB_URI": "@MONGODB_URI",
    "JWT_SECRET": "@JWT_SECRET",
    "EMAIL_USER": "@EMAIL_USER",
    "EMAIL_PASS": "@EMAIL_PASS",
    "PORT": "5000"
  }
}
